import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// components\layout.tsx
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="grow">
            <div className="">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
